services:
  qiandaizi:
    image: ghcr.io/qiancheng817/qiandaizi:latest
    container_name: qiandaizi
    restart: always
    ports:
      - 9600:9600
    environment:
      - TZ=Asia/Shanghai
      - PORT=9600
      - DATA_DIR=/app/data
      - JWT_SECRET=
      - ADMIN_USERNAME=
      - ADMIN_PASSWORD=
      - ALLOW_REGISTER=false
      - AI_BASE_URL=
      - AI_API_KEY=
      - AI_MODEL=
    volumes:
      - /vol1/1000/docker/qiandaizi/data:/app/data
